### ISSUE TITLE
Selected Value?

### ISSUE THREAD

**Issue by asnyder** [danielfarrell/bootstrap-combobox#122]
Due to the lack of documentation I'm having lots of trouble figuring out how to get the SelectedValue of the combobox.

For example, if I have:

```
<select id="add-holiday" class="custom_holiday"  >
<option value="">Enter Holiday</option>
<option value="1">President's Day</option>
<option value="2">Christmas</option>
<option value="3">Memorial Day</option>
</select>
```

After initializing via .combox(), if I add a change event and do $(this).val(), I end up getting the text, rather than the 1, 2, or 3. I see the options are in the map variable but I can't see an easy way to get at it. There must be something I'm missing. How can I get the Selected Value and how can I get the Selected Text?
</select>

**Comment by ruwen-m** [comment]
The library adds a hidden input with the same 'name' attribute like the original select. This input gets update by the library so you can get your desired value by $("[name='selectName']"). In your example:
```
<select id="add-holiday" class="custom_holiday" name="add-holiday">
<option value="">Enter Holiday</option>
<option value="1">President's Day</option>
<option value="2">Christmas</option>
<option value="3">Memorial Day</option>
</select>
```
Your script to get the value (via jquery):
`$("input[name='add-holiday']").val();`
