### ISSUE TITLE
Combobox disabled

### ISSUE THREAD

**Issue by lena773** [danielfarrell/bootstrap-combobox#192]
hallo, how can i make  combobox disabled/enabled. I've tried with document.getElementByid("element").disabled. Does not work

**Comment by ByroRedux** [comment]
You have to select the newly generated input[type=text] field, not your initial <select> or the input[type=hidden] element.
Combobox copies you initial select element classes, so just set a class and use it to select the combobox: $('input[type=text].myclass').prop('disabled', true);
