### ISSUE TITLE
Select value via string.

### ISSUE THREAD

**Issue by jeanpoelie** [danielfarrell/bootstrap-combobox#193]
Hi There,

I am very much liking this combobox, I also just found out that i can replace Chosen with this.
The only reason for me not to do this is because I cannot tell the dropdown to select everything that has the values, 3,4,5 for example.
I want to do something like $('#IDOFDROPDOWN').Select('3'); and that it will select this value for me. or on multiple, add it.

Is this, or could this be implemented? @danielfarrell

**Comment by danielfarrell** [comment]
I don't maintain this library anymore, so I will not be implementing that. If you implement it and make a PR it could get merged though.
