### ISSUE TITLE
Use a button addon group instead of a blank input addon group

### ISSUE THREAD

**Issue by MazeChaZer** [danielfarrell/bootstrap-combobox#198]
http://getbootstrap.com/components/#input-groups-buttons

This would show the user more directly that they can click in this area.

**Comment by Eonasdan** [comment]
My solution was to replace [line 183](https://github.com/danielfarrell/bootstrap-combobox/blob/master/js/bootstrap-combobox.js#L183) with this:
```
return '<div class="combobox-container"> <input type="hidden" /> <div class="input-group"> <input type="text" autocomplete="false" /> <span class="input-group-btn dropdown-toggle" data-dropdown="dropdown"><button class="btn btn-default">&nbsp;<span class="caret"></span><span class="glyphicon glyphicon-remove"></span>&nbsp;</button></span></div></div>';
```

**Comment by MazeChaZer** [comment]
This project doesn't seem interested in improvements, closing.
