### ISSUE TITLE
Please publish an official NPM package

### ISSUE THREAD

**Issue by dtaylor113** [danielfarrell/bootstrap-combobox#201]
Hi,
We use bootstrap-combobox as a dependency in our PatternFly toolkit (patternfly.org), however some of our consumers only use NPM to install PatternFly, so they currently can not get the bootstrap-combobox dependency since there isn't currently an official published NPM package for bootstrap-combobox.

We are planning on publishing an NPM for bootstrap-combobox, but it would be ideal if there was an official NPM.

Thanks,
- Dave Taylor

**Comment by pscheit** [comment]
+1 I really wanna use it in my build, thank you!

**Comment by Joe312341** [comment]
+1

**Comment by danielfarrell** [comment]
It's up on npm now as `@danielfarrell/bootstrap-combobox`.  Someone else had a `bootstrap-combobox` package already.
