### ISSUE TITLE
Check the files

### ISSUE THREAD

**Issue by pvnr0082t** [danielfarrell/bootstrap-combobox#209]
Hi @danielfarrell ,
I found that __bootstrap-combobox.js__ and __bootstrap-combobox.css__ v1.1.6 tagged are not the same as latest files in master branch. Could you please check or update it? Thank you.

https://github.com/cdnjs/cdnjs/pull/7735
https://github.com/cdnjs/cdnjs/issues/7664

**Comment by danielfarrell** [comment]
There just hasn't been a release done recently. I don't do most of the
maintenance here anymore, but I can cut another release if that is what is
wanted.

**Comment by danielfarrell** [comment]
Just tagged/released 1.1.7 based on current master.

**Comment by pvnr0082t** [comment]
Okay, thanks for your help.

**Comment by PeterDaveHello** [comment]
@danielfarrell hey sorry for bothering you, in fact, this is not a real issue, and didn't impact the process to host your lib on CDNJS. Still thanks for your kind reply.
