### ISSUE TITLE
How to disable combobox?

### ISSUE THREAD

**Issue by pratikthakare777** [danielfarrell/bootstrap-combobox#238]
How to disable combobox? I am using html disabled Attribute still data is populating from dropdown. I do not want to populate data. I need complete disable combobox nothing can populate or select able.
Please help me if there is any option present in bootstrap-combobox. Thanks For this amazing bootstrap-combobox.  

`<select class="combobox"  disabled >
  <option></option>
  <option value="PA">Pennsylvania</option>
  <option value="CT">Connecticut</option>
  <option value="NY">New York</option>
  <option value="MD">Maryland</option>
  <option value="VA">Virginia</option>
</select>`

**Comment by vanikin** [comment]
$('#element').data('combobox').disable()
You can enable it same way

**Comment by james-poulose** [comment]
Is it possible to disable selected options?

**Comment by tiesont** [comment]
@james-poulose Not sure what you mean - can you elaborate, please? Better yet, create a new issue, since it sounds like you're asking something that isn't entirely related to this issue, which is closed.
