### ISSUE TITLE
Update combobox via ajax

### ISSUE THREAD

**Issue by juanda99** [danielfarrell/bootstrap-combobox#25]
When I call it vía combobox() function, everything goes ok, and your control works awesome. The problem is when I update combo box data menu via ajax.

Your combo doen't realize about the changes. Only way is to call combobox() function after the ajax function, but is not the way I want (I think I can't call combobox() function more than once).

Any workaround? Any kind of help would be really appreciated.

**Comment by svaldenegro** [comment]
Is this solution still working?
