### ISSUE TITLE
Using Typeahead standalone

### ISSUE THREAD

**Issue by joelanman** [danielfarrell/bootstrap-combobox#99]
I'm currently using the typeahead standalone script, and combobox doesnt seem to work with it. Are there any known workarounds or fork to make it compatible? I've tried poking at the code and get these errors:

Line 44

Combobox.prototype = $.extend({}, $.fn.typeahead.Constructor.prototype, {

typeahead.Constructor doesn't exist (ltypeahead.constructor does)

Line 158

if (this.eventSupported('keydown')) {

eventSupported doesn't exist

**Comment by nickrivadeneira** [comment]
I know this is old, but for what it's worth, I was able to get typeahead.js and bootstrap-combobox working together by using [`noConflict()`](https://github.com/twitter/typeahead.js/blob/330f249428867f9353ecfa4d3997386390d07812/doc/jquery_typeahead.md#jqueryfntypeaheadnoconflict) and changing the [`menu` property](https://github.com/danielfarrell/bootstrap-combobox/blob/8663e275605c329de2faf82ac85f5b2bcc2e60ca/js/bootstrap-combobox.js#L456) to not use the `typeahead` class.
